export enum UserRole {
  ADMIN = 'admin',
  TENDER_MANAGER = 'tender_manager',
}

export enum WorkEnvironment {
  GAS = 'gas',
  LIQUID = 'liquid',
  MIXTURE = 'mixture',
}

export enum Drive {
  MANUAL = 'manual',
  FLYWHEEL = 'flywheel',
  GEARBOX = 'gearbox',
  PNEUMATIC = 'pneumatic',
  HYDRAULIC = 'hydraulic',
  ELECTRIC = 'electric',
  ELECTROHYDRAULIC = 'electrohudraulic',
  CHAIN_DRIVE = 'chain_drive',
}

export enum TypeZra {
  BOLT_ON_LID = 'BOLT_ON_LID',
  WEDGE_GATE_PARALLEL_SLIDING = 'WEDGE_GATE_PARALLEL_SLIDING',
  BELLOWS = 'BELLOWS',
  PRESSURE_SEAL_GATE = 'PRESSURE_SEAL_GATE',
  HIGH_PRESSURE_PARALLEL_SLIDING = 'HIGH_PRESSURE_PARALLEL_SLIDING',
  SPHERICAL_PIPELINE_GATE = 'SPHERICAL_PIPELINE_GATE',
  BOLTED_COVER = 'BOLTED_COVER',
  TYPE_Y = 'TYPE_Y',
  ANGULAR = 'ANGULAR',
  BELLOWS_VALVE = 'BELLOWS_VALVE',
  BELLOWS_TYPE_Y = 'BELLOWS_TYPE_Y',
  PRESSURE_SEAL_GLOBE = 'PRESSURE_SEAL_GLOBE',
  PRESSURE_SEAL_GLOBE_TYPE_Y = 'PRESSURE_SEAL_GLOBE_TYPE_Y',
  TURNING = 'TURNING',
  PISTON = 'PISTON',
  PISTON_TYPE_Y = 'PISTON_TYPE_Y',
  SWING_CHECK_PRESSURE_SEAL = 'SWING_CHECK_PRESSURE_SEAL',
  LIFT_CHECK_PRESSURE_SEAL_STRAIGHT = 'LIFT_CHECK_PRESSURE_SEAL_STRAIGHT',
  LIFT_CHECK_PRESSURE_SEAL_Y_PATTERN = 'LIFT_CHECK_PRESSURE_SEAL_Y_PATTERN',
  INCLINED_DISK = 'INCLINED_DISK',
  FLOATING_PLUG_SIDE_ENTRY = 'FLOATING_PLUG_SIDE_ENTRY',
  TRUNNION_BALL_SIDE_ENTRY = 'TRUNNION_BALL_SIDE_ENTRY',
  TRUNNION_BALL_TOP_ENTRY = 'TRUNNION_BALL_TOP_ENTRY',
  MONOBLOCK = 'MONOBLOCK',
  FLOATING_TWIN = 'FLOATING_TWIN',
  THREE_WAY = 'THREE_WAY',
  TWO_CENTERED = 'TWO_CENTERED',
  THREE_CENTERED = 'THREE_CENTERED',
}
