export const staticOptions = {
  manufacturingStandart: [
    { id: 1, name: "API 600" },
    {
      id: 2,
      name: "BS 1414",
    },
    {
      id: 3,
      name: "ASME B16.34",
    },
    {
      id: 4,
      name: "ISO 10434",
    },
    {
      id: 5,
      name: "API 602",
    },
  ],
  typeOfOrgan: [
    { id: 1, name: "ЖЕСТКИЙ КЛИН" },
    { id: 2, name: "ПОДВИЖНЫЙ КЛИН" },
    { id: 3, name: "ДВУХДИСКОВАЯ" },
    { id: 4, name: "ПАРАЛЛЕЛЬНЫЙ ДИСК" },
  ],
  diameters: [
    { id: 1, name: "1/2" },
    { id: 2, name: "3/4" },
    { id: 3, name: "1" },
    { id: 4, name: '1" 1/4' },
    { id: 5, name: '1" 1/2' },
    { id: 6, name: '2"' },
    { id: 7, name: '2" 1/2"' },
    { id: 8, name: '3"' },
    { id: 9, name: '4"' },
    { id: 10, name: '5"' },
    { id: 11, name: '6"' },
    { id: 12, name: '8"' },
    { id: 13, name: '10"' },
    { id: 14, name: '12"' },
    { id: 15, name: '14"' },
    { id: 16, name: '16"' },
    { id: 17, name: '18"' },
    { id: 18, name: '20"' },
    { id: 19, name: '24"' },
    { id: 20, name: '28"' },
    { id: 21, name: '30"' },
    { id: 22, name: '32"' },
    { id: 23, name: '36"' },
    { id: 24, name: '40"' },
    { id: 25, name: '42"' },
    { id: 26, name: '48"' },
  ],
  classPressures: [
    { id: 1, name: "150#" },
    { id: 2, name: "300#" },
    { id: 3, name: "600#" },
    { id: 4, name: "900#" },
    { id: 5, name: "1500#" },
    { id: 6, name: "2500#" },
  ],
  temperature: [
    { id: 1, name: "Стандартная (-46°C <= T <= +200°C)" },
    { id: 2, name: "Низкотемпературная (-60°C <= T <= +200°C)" },
    { id: 3, name: "Высокотемпературная (-46°C <= T <= +400°C)" },
    { id: 4, name: "Абразивная (-46°C <= T <= +200°C)" },
    { id: 5, name: "Низкотемпературная абразивная (-60°C <= T <= +200°C)" },
    { id: 6, name: "Высокотемпературная (T > +400°C)" },
    { id: 7, name: "Криогенная (-196°C <= T <= 50°C)" },
  ],
};
